/*
 * Data Repository Service
 *
 *  GET request:  - Fetch a DrsObject from the database by sending a unique ID through the request - Fetch an access url to the data which the object refers to - Fetch DrsObjects by doing a search on the aliases  POST request:  - Create a non-existing DrsObject in the database by giving an identifier  DELETE request:  - Delete a DrsObject from the database by unique identifier  PUT request:  - Update an existing DrsObject by unique identifier and the changes in the body 
 *
 * API version: 1.2.0
 * Contact: ict@cmgg.be
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package drs_api

type AccessUrl struct {
	// A fully resolvable URL that can be used to fetch the actual object bytes.
	Url string `json:"url"`
	// An optional list of headers to include in the HTTP request to ```url```.         These headers can be used to provide auth tokens required to fetch the object bytes.
	Headers []string `json:"headers,omitempty"`
}
