/*
 * Data Repository Service
 *
 *  GET request:  - Fetch a DrsObject from the database by sending a unique ID through the request - Fetch an access url to the data which the object refers to - Fetch DrsObjects by doing a search on the aliases  POST request:  - Create a non-existing DrsObject in the database by giving an identifier  DELETE request:  - Delete a DrsObject from the database by unique identifier  PUT request:  - Update an existing DrsObject by unique identifier and the changes in the body 
 *
 * API version: 1.2.0
 * Contact: ict@cmgg.be
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package drs_api

// The list of access methods that can be used to fetch the ```DrsObject```. Required for single blobs; optional for bundles.
type AllOfDrsObjectAccessMethods struct {
	// Enum: ```\"s3\"``` ```\"gs\"``` ```\"ftp\"``` ```\"gsiftp\"``` ```\"globus\"```         ```\"htsget\"``` ```\"https\"``` ```\"file\"``` Type of the access method.
	Type_ string `json:"type"`
	AccessUrl *AccessUrl `json:"access_url,omitempty"`
	// An arbitrary string to be passed to the ```/access``` method to get an ```AccessURL```.         This string must be unique within the scope of a single object. Note that at least one         of ```access_url``` and ```access_id``` must be provided.
	AccessId string `json:"access_id,omitempty"`
	// Name of the region in the cloud service provider that the object belongs to.
	Region string `json:"region,omitempty"`
}
